import { Router, type IRouter } from "express";
import healthRouter from "./health";
import uploadRouter from "./upload";
import uploadDocumentRouter from "./uploadDocument";
import estimateRouter from "./estimate";
import dealRoomsRouter from "./dealRoomsApi";
import leadsRouter from "./leads";
import accessRequestsRouter from "./accessRequests";
import fxRouter from "./fx";
import authRouter from "./auth";
import platformNdaRouter from "./platformNda";
import dealLegalRouter from "./dealLegal";
import dealCommissionRouter from "./dealCommission";
import userAdminRouter from "./userAdmin";
import yachtModerationRouter from "./yachtModeration";
import legalPagesRouter from "./legalPages";
import adminBadgeCountsRouter from "./adminBadgeCounts";
import adminAnalyticsRouter from "./adminAnalytics";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/upload-photo", uploadRouter);
router.use("/upload-document", uploadDocumentRouter);
router.use(estimateRouter);
router.use(dealRoomsRouter);
router.use("/leads", leadsRouter);
router.use("/access-requests", accessRequestsRouter);
router.use(fxRouter);
router.use(authRouter);
router.use(platformNdaRouter);
router.use(dealLegalRouter);
router.use(dealCommissionRouter);
router.use(userAdminRouter);
router.use(yachtModerationRouter);
router.use(legalPagesRouter);
router.use(adminBadgeCountsRouter);
router.use(adminAnalyticsRouter);

export default router;
