// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/brokers-page/DistressedCharcoal.tsx": () => import("../components/mockups/brokers-page/DistressedCharcoal.tsx"),
  "./components/mockups/brokers-page/MediterraneanEditorial.tsx": () => import("../components/mockups/brokers-page/MediterraneanEditorial.tsx"),
  "./components/mockups/brokers-page/NavyDiscipline.tsx": () => import("../components/mockups/brokers-page/NavyDiscipline.tsx")
};
